name: atm_tracker
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.2.2+1

environment:
  sdk: ">=3.0.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  logger: ^1.3.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  firebase_core: ^2.11.0
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.6.0
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1
  firebase_storage: ^11.2.1
  video_player: ^2.6.1
  flutter_launcher_icons: ^0.13.1
  firebase_analytics: ^10.4.3
  provider: ^6.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: MontserratNormal
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
